const LOGIN = 'LOGIN';
const API_ERROR = 'API_ERROR';
const LOGIN_FROM_LOCAL_STORAGE = 'LOGIN_FROM_LOCAL_STORAGE';
const LOAD_ALL_BOOKS = 'LOAD_ALL_BOOKS';
const LOG_OUT = 'LOG_OUT';

export { LOGIN, LOGIN_FROM_LOCAL_STORAGE, API_ERROR, LOAD_ALL_BOOKS, LOG_OUT };
