const LOGIN = 'LOGIN';
const API_ERROR = 'API_ERROR';
const LOGIN_FROM_LOCAL_STORAGE = 'LOGIN_FROM_LOCAL_STORAGE';
const LOAD_ALL_BOOKS = 'LOAD_ALL_BOOKS';
const LOG_OUT = 'LOG_OUT';
const LOAD_BOOK_BY_ID = 'LOAD_BOOK_BY_ID';
const CLEAR_SELECTED_BOOK = 'CLEAR_SELECTED_BOOK';
const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
const GET_FILTER_PRICE_VALUE = 'GET_FILTER_PRICE_VALUE';
const GET_FILTER_TITLE_VALUE = 'GET_FILTER_TITLE_VALUE';
const PLACE_ORDER = 'PLACE_ORDER';
const CLEAR_CART = 'CLEAR_CART';

export {
  LOGIN,
  LOGIN_FROM_LOCAL_STORAGE,
  API_ERROR,
  LOAD_ALL_BOOKS,
  LOG_OUT,
  LOAD_BOOK_BY_ID,
  CLEAR_SELECTED_BOOK,
  ADD_BOOK_TO_CART,
  GET_FILTER_PRICE_VALUE,
  GET_FILTER_TITLE_VALUE,
  PLACE_ORDER,
  CLEAR_CART,
};
